
CREATE TABLE STUDENT (
	STUDENT_NO NUMBER PRIMARY KEY,
	STUDENT_ID VARCHAR2(30) NOT NULL,
	STUDENT_PW VARCHAR2(30) NOT NULL,
	STUDENT_NM VARCHAR2(30) NOT NULL,
	STUDENT_GENDER CHAR(1) CHECK(STUDENT_GENDER IN ('M','F')),
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y','N'))
);

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '회원번호';
COMMENT ON COLUMN STUDENT.STUDENT_ID IS '회원 아이디';
COMMENT ON COLUMN STUDENT.STUDENT_PW IS '회원 비밀번호';
COMMENT ON COLUMN STUDENT.STUDENT_NM IS '회원 이름';
COMMENT ON COLUMN STUDENT.STUDENT_GENDER IS '회원 성별';
COMMENT ON COLUMN STUDENT.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN STUDENT.SECESSION_FL IS '탈퇴여부(Y/N)';

SELECT * FROM STUDENT;

CREATE SEQUENCE SEQ_NO NOCACHE;

INSERT INTO STUDENT VALUES(SEQ_NO.NEXTVAL, 'std01', 'pass01', '김길동', 'M', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES(SEQ_NO.NEXTVAL, 'std02', 'pass02', '이지인', 'F', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES(SEQ_NO.NEXTVAL, 'std03', 'pass03', '박주은', 'F', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES(SEQ_NO.NEXTVAL, 'std04', 'pass04', '서민준', 'M', DEFAULT, DEFAULT);

COMMIT;

SELECT STUDENT_NO, STUDENT_ID, STUDENT_NM, STUDENT_GENDER,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM STUDENT
WHERE STUDENT_ID = 'std01'
AND STUDENT_PW = 'pass01'
AND SECESSION_FL = 'N';





