---------< 메인화면 >----------
DROP TABLE STUDENT;
DROP SEQUENCE SEQ_NO_STD;
-- STUDENT 테이블 생성
CREATE TABLE STUDENT (
	STUDENT_NO NUMBER PRIMARY KEY,
	STUDENT_ID VARCHAR2(30) NOT NULL,
	STUDENT_PW VARCHAR2(30) NOT NULL,
	STUDENT_NM VARCHAR2(30) NOT NULL,
	STUDENT_GENDER CHAR(1) CHECK(STUDENT_GENDER IN ('M','F')),
	STUDENT_PHONE VARCHAR2(20) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y','N'))
);

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '회원번호';
COMMENT ON COLUMN STUDENT.STUDENT_ID IS '회원 아이디';
COMMENT ON COLUMN STUDENT.STUDENT_PW IS '회원 비밀번호';
COMMENT ON COLUMN STUDENT.STUDENT_NM IS '회원 이름';
COMMENT ON COLUMN STUDENT.STUDENT_GENDER IS '회원 성별';
COMMENT ON COLUMN STUDENT.STUDENT_PHONE IS '회원 전화번호';
COMMENT ON COLUMN STUDENT.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN STUDENT.SECESSION_FL IS '탈퇴여부(Y/N)';

-- SEQUENCE 생성
CREATE SEQUENCE SEQ_NO_STD NOCACHE;

-- STUDENT 샘플 데이터 삽입
INSERT INTO STUDENT VALUES(SEQ_NO_STD.NEXTVAL, 'std01', 'pass01', '김길동', 'M', '010-1234-1234', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES(SEQ_NO_STD.NEXTVAL, 'std02', 'pass02', '이지인', 'F', '010-1357-7073', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES(SEQ_NO_STD.NEXTVAL, 'std03', 'pass03', '박주은', 'F', '010-3490-4558', DEFAULT, DEFAULT);
INSERT INTO STUDENT VALUES(SEQ_NO_STD.NEXTVAL, 'std04', 'pass04', '서민준', 'M', '010-2050-4620', DEFAULT, DEFAULT);

COMMIT;

-- 로그인
SELECT STUDENT_NO, STUDENT_ID, STUDENT_NM, STUDENT_GENDER, STUDENT_PHONE,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM STUDENT
WHERE STUDENT_ID = 'std01'
AND STUDENT_PW = 'pass01'
AND SECESSION_FL = 'N';

SELECT * FROM STUDENT;
-- 회원가입
INSERT INTO STUDENT 
VALUES(SEQ_NO_STD.NEXTVAL, 'std05', 'pass05', '진미정', 'F', '010-1111-7777', DEFAULT, DEFAULT);

-- 아이디 중복 검사
SELECT COUNT(*)
FROM STUDENT
WHERE STUDENT_ID = 'std01'
AND SECESSION_FL = 'N';

-- 아이디 찾기
SELECT STUDENT_ID
FROM STUDENT
WHERE STUDENT_NM = '김길동'
AND STUDENT_PHONE = '010-1234-1234';


---------<공부 루틴 만들기>-------------

-- 루틴 명단 생성
CREATE TABLE ROUTINE(
	RT_NO NUMBER PRIMARY KEY,
	RT_NAME VARCHAR2(50) NOT NULL,
	STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN ROUTINE.RT_NO IS '루틴 번호';
COMMENT ON COLUMN ROUTINE.RT_NAME IS '루틴 이름';
COMMENT ON COLUMN ROUTINE.STUDENT_NO IS '회원 번호';

SELECT * FROM ROUTINE;

CREATE SEQUENCE SEQ_NO_RT NOCACHE;

INSERT INTO ROUTINE VALUES(SEQ_NO_RT.NEXTVAL, '복습하기', 1);
INSERT INTO ROUTINE VALUES(SEQ_NO_RT.NEXTVAL, '운동하기', 1);
INSERT INTO ROUTINE VALUES(SEQ_NO_RT.NEXTVAL, '6시 기상', 1);
INSERT INTO ROUTINE VALUES(SEQ_NO_RT.NEXTVAL, '아침 먹기', 2);
INSERT INTO ROUTINE VALUES(SEQ_NO_RT.NEXTVAL, '복습하기', 2);

SELECT RT_NO, RT_NAME, STUDENT_NO, STUDENT_NM
FROM ROUTINE
LEFT JOIN STUDENT USING(STUDENT_NO);

COMMIT;


--------<매일 기록 체크>-------------
-- 체크리스트 생성

CREATE TABLE CHECK_RT(
	CHECK_NO NUMBER PRIMARY KEY,
	RT_NO NUMBER REFERENCES ROUTINE(RT_NO) ON DELETE CASCADE,
	CHECK_RT VARCHAR2(10) NOT NULL,
	CHECK_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN CHECK_RT.CHECK_NO IS '체크 번호';
COMMENT ON COLUMN CHECK_RT.RT_NO IS '루틴 번호';
COMMENT ON COLUMN CHECK_RT.CHECK_RT IS '루틴 체크';
COMMENT ON COLUMN CHECK_RT.CHECK_DATE IS '기록 날짜';

SELECT * FROM CHECK_RT;

CREATE SEQUENCE SEQ_NO_CHECK NOCACHE;

SELECT TO_DATE('22/7/21') FROM DUAL;